# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='title',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, choices=[('Jerusalem', 'Jerusalem'), ('Tel Aviv', 'Tel Aviv'), ('Haifa', 'Haifa'), ('Eilat', 'Eilat')], default='j', help_text='Tutor area', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='charge',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hebrew', 'Hebrew'), ('Russian', 'Russian'), ('French', 'French'), ('Arabic', 'Arabic')], max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', help_text='Tutor availability', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(help_text='Enter a brief description about yourself', max_length=4000),
        ),
    ]
