# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170319_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, choices=[('Dark Arts', 'Dark Arts'), ('Charms', 'Charms'), ('Computer Science', 'Computer Science'), ('CSS Sorcery', 'CSS Sorcery')], default='', help_text='Tutor Subject', max_length=50),
        ),
    ]
