# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a language you speak (e.g. English, French, Hebrew etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a subject you want to teach (e.g. Math, Biology, Computer Science etc.)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, choices=[('Jerusalem', 'Jerusalem'), ('Tel Aviv', 'Tel Aviv'), ('Haifa', 'Haifa'), ('Eilat', 'Eilat')], default='', help_text='Tutor area', max_length=200),
        ),
    ]
