# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170319_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subject',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.ManyToManyField(help_text='Select a subject', related_name='tutor_type', to='accounts.Subject'),
        ),
    ]
