# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170319_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.ManyToManyField(default='', help_text='Select a subject', related_name='tutor_type', to='accounts.Subject'),
        ),
    ]
