# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170320_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/mystery-person-graphic.jpg', upload_to='profile_image'),
        ),
    ]
